back_end_news:
    resource: "@BackEndNewsBundle/Resources/config/routing.yml"
    prefix:   /

back_end_services_management:
    resource: "@BackEndServicesManagementBundle/Resources/config/routing.yml"
    prefix:   /

common_access:
    resource: "@CommonAccessBundle/Resources/config/routing.yml"
    prefix:   /

back_end_kids_management:
    resource: "@BackEndKidsManagementBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

redirect_login:
    path: /
    defaults: {_controller:CommonAccessBundle:main:redirectLogin}

