<?php

namespace BackEnd\KidsManagementBundle\Repository;

/**
 * CustodyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustodyRepository extends \Doctrine\ORM\EntityRepository
{
}
