<?php

namespace Common\AccessBundle\Repository;

/**
 * ParentOfKidsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentOfKidsRepository extends \Doctrine\ORM\EntityRepository
{
}
